<script setup>
import { computed, watch } from 'vue';
import { Head, Link, useForm, router } from '@inertiajs/vue3';
import AdminLayout from '@/Layouts/AdminLayout.vue';
import InputError from '@/Components/InputError.vue';
import RepairFields from '@/Components/RepairFields.vue';
const props = defineProps({ filters: Object, matches: Array, unitId: Number, check: Object, services: Object, statuses: Object, decisions: Object, faults: Object, today: String });
const isExternal = computed(() => props.filters.origin === 'external');
const serviceSearch = useForm({ search: props.filters.search || '' });
const findServices = () => router.get(route('watch-services.index'), { ...props.filters, search: serviceSearch.search }, { preserveScroll: true });
const lookup = useForm({ q: props.filters.q || '' });
const search = () => lookup.get(route('watch-services.index'), { preserveState: false });
const form = useForm({ watch_origin: isExternal.value ? 'external' : 'inventory', service_type: 'repair', external_name: '', external_brand: '', external_model: '', external_serial: '', fault_type: 'unknown', diagnosis: '', repair_provider: 'in_house', external_shop_name: '', external_shop_phone: '', external_reference: '', provider_notes: '', billing_status: 'pending', customer_charge: null, charge_notes: '', product_item_id: props.unitId, contact_name: props.check?.customer_name || '', contact_phone: props.check?.customer_phone || '', issue_date: props.today, issue_description: '', notes: '' });
watch(() => props.unitId, () => { form.product_item_id = props.unitId; form.contact_name = props.check?.customer_name || ''; form.contact_phone = props.check?.customer_phone || ''; });
const save = () => form.post(route('watch-services.store'));
const date = value => value ? value.substring(0, 10) : 'Not available';
const filterStatus = event => router.get(route('watch-services.index'), { ...props.filters, status: event.target.value || undefined }, { preserveScroll: true });
</script>
<template>
    <Head title="Repairs & Service" />
    <AdminLayout>
        <div class="mx-auto max-w-6xl space-y-6">
            <header><p class="text-xs font-semibold uppercase tracking-widest text-gold-700">Customer care</p><h1 class="mt-2 text-3xl font-bold text-gray-900">Repairs &amp; Service</h1><p class="mt-2 text-sm text-gray-500">Repair watches from Time On You or elsewhere. Track faults, repair shops, customer charges, and expenses.</p></header>
            <div class="grid gap-3 sm:grid-cols-2"><Link :href="route('watch-services.index', { origin: 'inventory' })" class="rounded-xl border p-4" :class="!isExternal ? 'border-gold-500 bg-gold-50' : 'bg-white border-gray-200'"><p class="font-semibold">Watch in our inventory</p><p class="mt-1 text-sm text-gray-500">Find its barcode, serial, or sales invoice.</p></Link><Link :href="route('watch-services.index', { origin: 'external' })" class="rounded-xl border p-4" :class="isExternal ? 'border-gold-500 bg-gold-50' : 'bg-white border-gray-200'"><p class="font-semibold">Outside watch / walk-in repair</p><p class="mt-1 text-sm text-gray-500">For a watch bought elsewhere, enter its details here.</p></Link></div>
            <section v-if="!isExternal" class="rounded-xl border bg-white p-5 shadow-sm">
                <form @submit.prevent="search" class="flex flex-col gap-3 sm:flex-row sm:items-end"><div class="min-w-0 flex-1"><label for="warranty-search" class="text-sm font-medium text-gray-700">Scan a unit barcode, or enter the full serial / invoice number</label><input id="warranty-search" v-model="lookup.q" required maxlength="255" class="mt-2 block w-full rounded-lg border-gray-300" placeholder="Barcode, manufacturer serial, or invoice number" autofocus><InputError :message="lookup.errors.q" /></div><button :disabled="lookup.processing" class="rounded-lg bg-gray-900 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Find watch</button></form>
                <p v-if="filters.q && !matches.length" class="mt-4 text-sm text-amber-800" role="status">No matching watch found. Use the barcode for an individual watch, not the model barcode.</p>
                <div v-if="matches.length" class="mt-4 grid gap-3 sm:grid-cols-2"><Link v-for="unit in matches" :key="unit.id" :href="route('watch-services.index', { q: filters.q, unit_id: unit.id })" class="rounded-lg border p-3 hover:bg-gold-50" :class="unit.id === unitId ? 'border-gold-500 bg-gold-50' : 'border-gray-200'"><p class="font-medium text-gray-900">{{ unit.name }}</p><p class="mt-1 break-all text-xs text-gray-500">Barcode: {{ unit.barcode || 'Not recorded' }} · Serial: {{ unit.serial_number || 'Not recorded' }}</p></Link></div>
                <p v-if="matches.length === 25" class="mt-2 text-xs text-gray-500">Showing the first 25 watches. Use a unit barcode or serial to narrow the result.</p>
            </section>

            <template v-if="check || isExternal">
                <section v-if="check" class="rounded-xl border bg-white p-5 shadow-sm">
                    <div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="text-xl font-semibold text-gray-900">{{ check.product_name }}</h2><p class="mt-1 text-sm text-gray-500">Barcode {{ check.barcode || 'not recorded' }} · Serial {{ check.serial_number || 'not recorded' }}</p></div><span class="rounded-full px-3 py-1.5 text-sm font-semibold" :class="check.result === 'within_period' ? 'bg-emerald-50 text-emerald-800' : 'bg-amber-50 text-amber-800'">{{ check.label }}</span></div>
                    <dl class="mt-5 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-gray-500">Purchaser</dt><dd class="mt-1 font-medium">{{ check.customer_name || 'Guest / not linked' }}</dd></div><div><dt class="text-gray-500">Customer purchase date</dt><dd class="mt-1 font-medium">{{ date(check.purchase_date) }}</dd><Link v-if="check.order_id" :href="route('orders.show', check.order_id)" class="text-xs text-gold-700 underline">{{ check.order_number }}</Link></div><div><dt class="text-gray-500">Warranty period</dt><dd class="mt-1 font-medium">{{ check.warranty_months ?? 'Unknown' }} months</dd><dd class="mt-1 text-xs text-gray-500">{{ check.warranty_type?.replaceAll('_', ' ') || 'Type not recorded' }}</dd></div><div><dt class="text-gray-500">Warranty end date</dt><dd class="mt-1 font-medium">{{ date(check.expires_on) }}</dd></div></dl>
                    <p class="mt-4 rounded-lg bg-gray-50 p-3 text-xs leading-5 text-gray-600">Checked as of {{ check.checked_on }}, using the completed invoice date and current product warranty settings. Damage and fault coverage still require an administrator's review. Missing purchase proof can be documented in service notes.</p>
                </section>
                <section class="rounded-xl border bg-white p-5 shadow-sm"><h2 class="text-lg font-semibold text-gray-900">New repair job</h2><p class="mt-1 text-sm text-gray-500">Describe the watch and the work requested. Warranty review is optional.</p>
                    <form @submit.prevent="save" class="mt-5 space-y-4">
                        <div><label for="service-type" class="text-sm font-medium">Type of service</label><select id="service-type" v-model="form.service_type" class="mt-1 block w-full rounded-lg border-gray-300"><option value="repair">General repair / maintenance</option><option value="warranty">Warranty review and service</option></select><InputError :message="form.errors.service_type" /></div>
                        <fieldset v-if="isExternal" class="rounded-xl border border-gray-200 p-4"><legend class="px-1 text-sm font-semibold">Outside watch details</legend><div class="grid gap-4 sm:grid-cols-2"><div><label for="outside-name" class="text-sm font-medium">Watch description</label><input id="outside-name" v-model="form.external_name" required maxlength="255" class="mt-1 block w-full rounded-lg border-gray-300" placeholder="e.g. Silver automatic watch"><InputError :message="form.errors.external_name" /></div><div><label for="outside-brand" class="text-sm font-medium">Brand (optional)</label><input id="outside-brand" v-model="form.external_brand" maxlength="255" class="mt-1 block w-full rounded-lg border-gray-300"><InputError :message="form.errors.external_brand" /></div><div><label for="outside-model" class="text-sm font-medium">Model (optional)</label><input id="outside-model" v-model="form.external_model" maxlength="255" class="mt-1 block w-full rounded-lg border-gray-300"><InputError :message="form.errors.external_model" /></div><div><label for="outside-serial" class="text-sm font-medium">Serial / identifying marks (optional)</label><input id="outside-serial" v-model="form.external_serial" maxlength="255" class="mt-1 block w-full rounded-lg border-gray-300"><InputError :message="form.errors.external_serial" /></div></div></fieldset>
                        <div class="grid gap-4 sm:grid-cols-3"><div><label for="service-contact" class="text-sm font-medium">Contact name</label><input id="service-contact" v-model="form.contact_name" required maxlength="255" class="mt-1 block w-full rounded-lg border-gray-300"><InputError :message="form.errors.contact_name" /></div><div><label for="service-phone" class="text-sm font-medium">Contact phone (optional)</label><input id="service-phone" v-model="form.contact_phone" maxlength="50" class="mt-1 block w-full rounded-lg border-gray-300"><InputError :message="form.errors.contact_phone" /></div><div><label for="service-date" class="text-sm font-medium">Date received</label><input id="service-date" v-model="form.issue_date" type="date" required :max="today" :min="check?.purchase_date || undefined" class="mt-1 block w-full min-w-0 rounded-lg border-gray-300"><InputError :message="form.errors.issue_date" /></div></div>
                        <div><label for="service-issue" class="text-sm font-medium">What is wrong with the watch?</label><textarea id="service-issue" v-model="form.issue_description" required maxlength="10000" rows="3" class="mt-1 block w-full rounded-lg border-gray-300" placeholder="Describe the issue, visible damage, and items received."></textarea><InputError :message="form.errors.issue_description" /></div>
                        <div><label for="service-notes" class="text-sm font-medium">Additional notes (optional)</label><textarea id="service-notes" v-model="form.notes" maxlength="10000" rows="2" class="mt-1 block w-full rounded-lg border-gray-300" placeholder="Receipt details, accessories handed over, or customer instructions."></textarea><InputError :message="form.errors.notes" /></div>
                        <RepairFields :form="form" :faults="faults" /><InputError :message="form.errors.watch_origin" /><InputError :message="form.errors.product_item_id" /><button :disabled="form.processing" class="rounded-lg bg-gold-500 px-5 py-2.5 text-sm font-semibold text-gray-900 disabled:opacity-50">{{ form.processing ? 'Saving…' : 'Create repair job' }}</button>
                    </form>
                </section>
            </template>

            <section class="overflow-hidden rounded-xl border bg-white shadow-sm"><div class="flex flex-wrap items-center justify-between gap-3 p-5"><div><h2 class="text-lg font-semibold text-gray-900">{{ unitId ? 'Repair jobs for this watch' : 'Repair jobs' }}</h2><Link v-if="unitId" :href="route('watch-services.index')" class="text-xs text-gold-700 underline">View all watches</Link></div><select aria-label="Filter services by status" :value="filters.status || ''" @change="filterStatus" class="rounded-lg border-gray-300 text-sm"><option value="">All statuses</option><option v-for="(label, status) in statuses" :key="status" :value="status">{{ label }}</option></select></div>
                <form @submit.prevent="findServices" class="flex gap-2 px-5 pb-4"><input v-model="serviceSearch.search" aria-label="Search repair records" maxlength="255" class="min-w-0 flex-1 rounded-lg border-gray-300 text-sm" placeholder="Job number, contact name, phone, or watch description"><button class="rounded-lg bg-gray-100 px-4 text-sm font-medium">Search jobs</button></form><div class="divide-y border-t md:hidden"><Link v-for="service in services.data" :key="service.id" :href="route('watch-services.show', service.id)" class="block space-y-3 p-5 hover:bg-gray-50"><div class="flex items-start justify-between gap-3"><span class="font-semibold text-gold-700">Repair #{{ service.id }}</span><span class="rounded-full bg-gray-100 px-3 py-1 text-xs font-medium text-gray-700">{{ statuses[service.status] }}</span></div><p class="break-words font-medium text-gray-900">{{ service.warranty_snapshot.product_name }}</p><p class="text-sm text-gray-600">{{ service.contact_name }} · {{ date(service.issue_date) }}</p><p class="text-sm text-gray-700">{{ service.billing_status === 'pending' ? 'Charge not decided' : service.billing_status === 'free' ? 'Free of charge' : Number(service.customer_charge).toLocaleString() + ' MMK' }}</p><p class="text-xs text-gray-500">Repair location: {{ service.repair_provider === 'external' ? service.external_shop_name : 'Time On You' }}</p></Link><p v-if="!services.data.length" class="p-8 text-center text-sm text-gray-500">No repair jobs found. Try a different name or status.</p></div><div class="hidden overflow-x-auto md:block"><table class="w-full text-left text-sm"><thead class="bg-gray-50 text-xs uppercase text-gray-500"><tr><th class="px-5 py-3">Repair / watch</th><th class="px-5 py-3">Contact</th><th class="px-5 py-3">Received</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Charge / repair location</th></tr></thead><tbody class="divide-y"><tr v-for="service in services.data" :key="service.id"><td class="px-5 py-4"><Link :href="route('watch-services.show', service.id)" class="font-semibold text-gold-700 hover:underline">Repair #{{ service.id }}</Link><p class="mt-1 text-xs text-gray-500">{{ service.warranty_snapshot.product_name }} · {{ service.warranty_snapshot.barcode }}</p></td><td class="px-5 py-4">{{ service.contact_name }}</td><td class="whitespace-nowrap px-5 py-4">{{ date(service.issue_date) }}</td><td class="px-5 py-4">{{ statuses[service.status] }}</td><td class="px-5 py-4">{{ service.billing_status === 'pending' ? 'Charge undecided' : service.billing_status === 'free' ? 'Free service' : Number(service.customer_charge).toLocaleString() + ' MMK' }}<p class="mt-1 text-xs text-gray-500">{{ service.repair_provider === 'external' ? service.external_shop_name : 'Time On You' }}</p></td></tr><tr v-if="!services.data.length"><td colspan="5" class="p-10 text-center text-gray-500">No repair jobs found. Try a different name or status.</td></tr></tbody></table></div>
                <div v-if="services.last_page > 1" class="flex items-center justify-between border-t p-4 text-sm"><Link v-if="services.prev_page_url" :href="services.prev_page_url" class="text-gold-700">Previous</Link><span v-else /><span>Page {{ services.current_page }} of {{ services.last_page }}</span><Link v-if="services.next_page_url" :href="services.next_page_url" class="text-gold-700">Next</Link><span v-else /></div>
            </section>
        </div>
    </AdminLayout>
</template>
