<script setup>
import { computed, nextTick, ref, watch } from 'vue';
import { Head, Link, useForm } from '@inertiajs/vue3';
import AdminLayout from '@/Layouts/AdminLayout.vue';
import InputError from '@/Components/InputError.vue';
import RepairFields from '@/Components/RepairFields.vue';
import ServiceTimeline from '@/Components/ServiceTimeline.vue';
import RepairPrintSlip from '@/Components/RepairPrintSlip.vue';
const props = defineProps({ service: Object, currentCheck: Object, statuses: Object, decisions: Object, faults: Object, today: String, expenseTotal: [String, Number], expectedMargin: [String, Number] });
const activeSection = ref('overview');
const includePrintExpenses = ref(false);
const printedOn = ref(new Date().toLocaleString('en-GB'));
const printRepair = async () => { printedOn.value = new Date().toLocaleString('en-GB'); await nextTick(); window.print(); };
const sections = [{ id: 'overview', label: 'Overview & timeline' }, { id: 'update', label: 'Update repair' }, { id: 'expenses', label: 'Expenses' }, { id: 'print', label: 'Print slip' }];
const statusHint = computed(() => ({ received: 'The watch has been received. Record the inspection findings when ready.', inspection: 'The watch is being checked to find the problem.', awaiting_approval: 'Waiting for the customer to approve the work.', sent_to_company: 'The watch has been sent to the company for repair.', sent_to_shop: 'The watch has been sent to another repair shop.', external_repair: 'Another shop is working on the repair.', returned_from_shop: 'The watch is back from the other shop.', repairing: 'Repair work is in progress.', ready: 'The watch is ready for the customer to collect.', completed: 'This repair job is complete.', cancelled: 'This repair job has been cancelled.' }[props.service.status]));
const snapshot = computed(() => props.service.warranty_snapshot);
const repairKeys = ['fault_type', 'diagnosis', 'repair_provider', 'external_shop_name', 'external_shop_phone', 'external_reference', 'provider_notes', 'billing_status', 'customer_charge', 'charge_notes'];
const form = useForm({ ...Object.fromEntries(repairKeys.map(key => [key, props.service[key]])), status: props.service.status, coverage_decision: props.service.coverage_decision, decision_notes: props.service.decision_notes || '', notes: '', last_event_id: props.service.events[0]?.id });
watch(() => props.service, service => { for (const key of repairKeys) form[key] = service[key]; form.status = service.status; form.coverage_decision = service.coverage_decision; form.decision_notes = service.decision_notes || ''; form.last_event_id = service.events[0]?.id; });
const save = () => form.put(route('watch-services.update', props.service.id), { preserveScroll: true, onSuccess: () => { form.reset('notes'); activeSection.value = 'overview'; } });
const date = value => value ? new Date(value.substring(0, 10) + 'T00:00:00').toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }) : 'Not recorded';
const money = value => Number(value || 0).toLocaleString('en-US', { maximumFractionDigits: 2 });
const expenseForm = useForm({ request_id: crypto.randomUUID(), amount: '', expense_date: props.today, description: '', paid_to: '' });
const addExpense = () => expenseForm.post(route('watch-services.expenses.store', props.service.id), { preserveScroll: true, onSuccess: () => { expenseForm.reset(); expenseForm.request_id = crypto.randomUUID(); } });
const voidForm = useForm({ void_reason: '' });
const voidId = ref(null);
const voidExpense = () => voidForm.patch(route('watch-services.expenses.void', [props.service.id, voidId.value]), { preserveScroll: true, onSuccess: () => { voidId.value = null; voidForm.reset(); } });

</script>
<template>
    <Head :title="`Service #${service.id}`" />
    <AdminLayout>
        <div class="mx-auto max-w-6xl space-y-6">
            <header class="space-y-5">
                <Link :href="route('watch-services.index')" class="text-sm font-medium text-gold-700 hover:underline">← All repair jobs</Link>
                <div class="flex flex-wrap items-start justify-between gap-4">
                    <div class="min-w-0"><h1 class="text-2xl font-bold text-gray-900 sm:text-3xl">Repair #{{ service.id }}</h1><p class="mt-2 break-words text-lg text-gray-700">{{ snapshot.product_name }}</p><p class="mt-1 text-sm text-gray-500">{{ service.contact_name }} · {{ service.watch_origin === 'external' ? 'Watch brought from elsewhere' : 'Watch in our inventory' }} · {{ service.service_type === 'repair' ? 'General repair' : 'Warranty service' }}</p></div>
                    <div class="flex flex-wrap gap-2"><button type="button" @click="activeSection = 'print'" class="rounded-xl border border-gray-300 bg-white px-5 py-3 text-sm font-semibold text-gray-700 hover:bg-gray-50">Print repair slip</button><button v-if="activeSection !== 'update'" type="button" @click="activeSection = 'update'" class="rounded-xl bg-gray-900 px-5 py-3 text-sm font-semibold text-white hover:bg-gray-800">Update repair</button></div>
                </div>
                <div class="rounded-xl border p-4" :class="service.status === 'completed' || service.status === 'ready' ? 'border-emerald-200 bg-emerald-50' : 'border-gray-200 bg-white'"><p class="text-xs font-medium text-gray-500">Current progress</p><p class="mt-1 font-semibold text-gray-900">{{ statuses[service.status] }}</p><p class="mt-1 text-sm text-gray-600">{{ statusHint }}</p></div>
            </header>
            <nav aria-label="Repair sections" class="flex gap-1 overflow-x-auto rounded-xl border border-gray-200 bg-gray-100 p-1">
                <button v-for="section in sections" :key="section.id" type="button" :aria-pressed="activeSection === section.id" :aria-controls="`repair-${section.id}`" @click="activeSection = section.id" class="flex-1 whitespace-nowrap rounded-lg px-3 py-3 text-sm font-semibold transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-gold-500" :class="activeSection === section.id ? 'bg-white text-gray-900 shadow-sm' : 'text-gray-600 hover:bg-white/60'">{{ section.label }}</button>
            </nav>
            <div v-show="activeSection === 'overview'" id="repair-overview" class="space-y-6">
            <div class="grid gap-4 sm:grid-cols-3"><section class="rounded-xl border bg-white p-5"><p class="text-sm text-gray-500">Customer charge</p><p class="mt-2 text-xl font-semibold">{{ service.billing_status === 'pending' ? 'Not decided' : service.billing_status === 'free' ? 'Free of charge' : money(service.customer_charge) + ' MMK' }}</p><p v-if="service.charge_notes" class="mt-2 whitespace-pre-wrap break-words text-xs text-gray-500">{{ service.charge_notes }}</p></section><section class="rounded-xl border bg-white p-5"><p class="text-sm text-gray-500">Repair expenses</p><p class="mt-2 text-xl font-semibold">{{ money(expenseTotal) }} MMK</p><p class="mt-2 text-xs text-gray-500">Total spent on parts, repair shops, and other costs</p></section><section class="rounded-xl border bg-white p-5"><p class="text-sm text-gray-500">Amount after expenses</p><p class="mt-2 text-xl font-semibold" :class="Number(expectedMargin) < 0 ? 'text-red-700' : 'text-gray-900'">{{ expectedMargin === null ? 'Not available yet' : money(expectedMargin) + ' MMK' }}</p><p class="mt-2 text-xs text-gray-500">Customer charge minus expenses. Payment received is tracked separately.</p></section></div>
            <div class="grid gap-6 lg:grid-cols-2">
                <section class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="text-lg font-semibold">Customer &amp; watch</h2><p v-if="service.watch_origin === 'external'" class="mt-2 text-sm text-gray-500">{{ [snapshot.brand, snapshot.model].filter(Boolean).join(' · ') || 'No brand / model recorded' }}</p><dl class="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-gray-500">Watch barcode / serial number</dt><dd class="mt-1 break-all">{{ snapshot.barcode || 'Not recorded' }} / {{ snapshot.serial_number || 'Not recorded' }}</dd></div><div><dt class="text-gray-500">Original buyer</dt><dd class="mt-1">{{ snapshot.customer_name || 'No buyer recorded' }}</dd></div><div><dt class="text-gray-500">Customer contact</dt><dd class="mt-1">{{ service.contact_name }}</dd><dd>{{ service.contact_phone || 'No phone recorded' }}</dd></div><div><dt class="text-gray-500">Date received</dt><dd class="mt-1">{{ date(service.issue_date) }}</dd></div></dl><h3 class="mt-5 text-sm font-semibold">Problem reported by the customer</h3><p class="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-gray-600">{{ service.issue_description }}</p></section>
                <section class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="text-lg font-semibold">Repair details</h2><p class="mt-3 font-medium">{{ faults[service.fault_type] }}</p><p class="mt-2 whitespace-pre-wrap break-words text-sm text-gray-600">{{ service.diagnosis || 'The watch has not been assessed yet.' }}</p><h3 class="mt-4 text-sm font-semibold">Repair location</h3><p class="mt-2 text-sm">{{ service.repair_provider === 'external' ? service.external_shop_name : 'Time On You' }}</p><p v-if="service.repair_provider === 'external'" class="mt-2 text-sm text-gray-500">{{ service.external_shop_phone || 'No shop phone recorded' }} · Reference: {{ service.external_reference || 'Not recorded' }}</p><p class="mt-2 whitespace-pre-wrap break-words text-sm text-gray-500">{{ service.provider_notes }}</p></section>
                <section v-if="service.service_type === 'warranty'" class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm sm:p-6 lg:col-span-2"><h2 class="text-lg font-semibold">Warranty information</h2><p class="mt-3 font-semibold" :class="snapshot.result === 'within_period' ? 'text-emerald-700' : 'text-amber-700'">{{ snapshot.label }}</p><dl class="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-gray-500">Customer purchase date</dt><dd class="mt-1">{{ date(snapshot.purchase_date) }}</dd><Link v-if="service.order_id" :href="route('orders.show', service.order_id)" class="text-gold-700 underline">{{ snapshot.order_number }}</Link></div><div><dt class="text-gray-500">Warranty end date</dt><dd class="mt-1">{{ date(snapshot.expires_on) }}</dd></div><div><dt class="text-gray-500">Warranty terms</dt><dd class="mt-1">{{ snapshot.warranty_months ?? 'Unknown' }} months · {{ snapshot.warranty_type?.replaceAll('_', ' ') || 'Type not recorded' }}</dd></div><div><dt class="text-gray-500">Warranty decision</dt><dd class="mt-1 font-medium">{{ decisions[service.coverage_decision] }}</dd></div></dl><p v-if="service.decision_notes" class="mt-4 whitespace-pre-wrap break-words rounded-lg bg-gray-50 p-3 text-sm text-gray-600">{{ service.decision_notes }}</p><p class="mt-4 text-xs leading-5 text-gray-500">Warranty information recorded on {{ date(snapshot.checked_on) }}. Staff decide whether the repair is covered after checking the problem and proof of purchase.</p><p v-if="currentCheck" class="mt-2 text-xs text-gray-500">Warranty check today: {{ currentCheck.label }}.</p></section>
            </div>
                <ServiceTimeline :events="service.events" :statuses="statuses" :decisions="decisions" :faults="faults" :warranty="service.service_type === 'warranty'" />
            </div>
            <section v-show="activeSection === 'update'" id="repair-update" class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="text-lg font-semibold">Update this repair</h2><p class="mt-1 text-sm text-gray-500">Choose the current progress and describe what happened. Your update will appear in the timeline.</p><form @submit.prevent="save" class="mt-5 space-y-4"><div class="grid gap-4 sm:grid-cols-2"><div><label for="service-status" class="text-sm font-medium">Current progress</label><select id="service-status" v-model="form.status" class="mt-1 block w-full rounded-lg border-gray-300"><option v-for="(label, key) in statuses" :key="key" :value="key">{{ label }}</option></select><InputError :message="form.errors.status" /></div><div v-if="service.service_type === 'warranty'"><label for="service-coverage" class="text-sm font-medium">Warranty decision</label><select id="service-coverage" v-model="form.coverage_decision" class="mt-1 block w-full rounded-lg border-gray-300"><option v-for="(label, key) in decisions" :key="key" :value="key">{{ label }}</option></select><InputError :message="form.errors.coverage_decision" /></div></div><div v-if="service.service_type === 'warranty' || ['approved', 'rejected'].includes(form.coverage_decision)"><label for="decision-notes" class="text-sm font-medium">Reason for warranty decision {{ ['approved', 'rejected'].includes(form.coverage_decision) ? '(required)' : '(optional)' }}</label><textarea id="decision-notes" v-model="form.decision_notes" :required="['approved', 'rejected'].includes(form.coverage_decision)" maxlength="10000" rows="2" class="mt-1 block w-full rounded-lg border-gray-300" placeholder="Inspection findings, proof of purchase, or reason for approving/declining coverage."></textarea><InputError :message="form.errors.decision_notes" /></div><RepairFields :form="form" :faults="faults" /><div><label for="update-notes" class="text-sm font-medium">What happened? (required)</label><textarea id="update-notes" v-model="form.notes" required maxlength="10000" rows="3" class="mt-1 block w-full rounded-lg border-gray-300" placeholder="e.g. Replaced the battery and tested the watch. Called the customer to arrange collection."></textarea><InputError :message="form.errors.notes" /><InputError :message="form.errors.last_event_id" /></div><button :disabled="form.processing" class="rounded-lg bg-gray-900 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{{ form.processing ? 'Saving…' : 'Save update' }}</button></form></section>
            <section v-show="activeSection === 'expenses'" id="repair-expenses" class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm sm:p-6"><div class="flex flex-wrap items-start justify-between gap-3"><h2 class="text-lg font-semibold">Repair expenses</h2><span class="rounded-lg bg-gray-100 px-3 py-2 text-sm font-semibold">Total: {{ money(expenseTotal) }} MMK</span></div><p class="mt-1 text-sm text-gray-500">Record what Time On You spends on this job. Expenses are separate from the customer charge.</p><form @submit.prevent="addExpense" class="mt-5 space-y-4"><div class="grid gap-4 sm:grid-cols-3"><div><label for="expense-amount" class="text-sm font-medium">Amount (MMK)</label><input id="expense-amount" v-model="expenseForm.amount" required type="number" min="0.01" max="999999999999.99" step="0.01" class="mt-1 block w-full rounded-lg border-gray-300"><InputError :message="expenseForm.errors.amount" /></div><div><label for="expense-date" class="text-sm font-medium">Expense date</label><input id="expense-date" v-model="expenseForm.expense_date" required type="date" :min="service.issue_date.substring(0, 10)" :max="today" class="mt-1 block w-full min-w-0 rounded-lg border-gray-300"><InputError :message="expenseForm.errors.expense_date" /></div><div><label for="expense-payee" class="text-sm font-medium">Paid to (optional)</label><input id="expense-payee" v-model="expenseForm.paid_to" maxlength="255" class="mt-1 block w-full rounded-lg border-gray-300"><InputError :message="expenseForm.errors.paid_to" /></div></div><div><label for="expense-description" class="text-sm font-medium">Expense description</label><input id="expense-description" v-model="expenseForm.description" required maxlength="1000" placeholder="e.g. Outside repair fee, replacement battery, transport" class="mt-1 block w-full rounded-lg border-gray-300"><InputError :message="expenseForm.errors.description" /></div><InputError :message="expenseForm.errors.request_id" /><button :disabled="expenseForm.processing" class="rounded-lg bg-gray-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{{ expenseForm.processing ? 'Saving…' : 'Add expense' }}</button></form>
                <div class="mt-6 divide-y border-t"><div v-for="expense in service.expenses" :key="expense.id" class="py-4"><div class="flex flex-wrap justify-between gap-3"><div><p class="font-medium" :class="expense.voided_at ? 'text-gray-400 line-through' : 'text-gray-800'">{{ money(expense.amount) }} MMK · {{ expense.description }}</p><p class="mt-1 text-xs text-gray-500">{{ date(expense.expense_date) }} · {{ expense.paid_to || 'Payee not recorded' }} · Expense #{{ expense.id }}</p><p v-if="expense.voided_at" class="mt-2 text-xs text-red-700">Cancelled — excluded from total: {{ expense.void_reason }}</p></div><button v-if="!expense.voided_at" type="button" class="text-sm text-red-700 underline" @click="voidId = expense.id; voidForm.reset(); voidForm.clearErrors()">Cancel incorrect expense</button></div><form v-if="voidId === expense.id" @submit.prevent="voidExpense" class="mt-3 space-y-3 rounded-xl border border-red-100 bg-red-50 p-4"><p class="text-sm leading-6 text-gray-700">This removes {{ money(expense.amount) }} MMK from the expense total. The original entry stays in the history. It does not refund a payment.</p><label :for="`void-reason-${expense.id}`" class="text-sm">Why is this expense incorrect?</label><input :id="`void-reason-${expense.id}`" v-model="voidForm.void_reason" required maxlength="1000" class="block w-full rounded-lg border-gray-300"><InputError :message="voidForm.errors.void_reason" /><div class="flex gap-3"><button :disabled="voidForm.processing" class="rounded bg-red-700 px-3 py-2 text-sm text-white">Confirm cancellation</button><button type="button" @click="voidId = null" class="text-sm text-gray-600">Keep expense</button></div></form></div><p v-if="!service.expenses?.length" class="py-6 text-center text-sm text-gray-500">No expenses recorded yet.</p></div>
            </section>

            <section v-show="activeSection === 'print'" id="repair-print" class="space-y-4">
                <div class="rounded-2xl border border-gray-200 bg-white p-5">
                    <h2 class="text-lg font-semibold">Print repair slip</h2><p class="mt-1 text-sm text-gray-500">Preview the saved repair details below. Print on A4 paper or choose Save as PDF in the print dialog.</p>
                    <p v-if="form.isDirty" class="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">You have unsaved repair changes. Save your update first if you want those changes on the slip.</p>
                    <label class="mt-4 flex items-start gap-3 text-sm text-gray-700"><input v-model="includePrintExpenses" type="checkbox" class="mt-0.5 rounded border-gray-300 text-gray-900"><span>Include shop expenses (internal shop copy)<span class="mt-1 block text-xs text-gray-500">The customer copy includes their charge and its reason. This option also shows internal costs and instructions for the other shop.</span></span></label>
                    <button type="button" @click="printRepair" class="mt-4 rounded-lg bg-gray-900 px-5 py-2.5 text-sm font-semibold text-white">Print / Save as PDF</button>
                </div>
                <RepairPrintSlip class="rounded-xl border border-gray-200" :service="service" :statuses="statuses" :decisions="decisions" :faults="faults" :include-expenses="includePrintExpenses" :expense-total="expenseTotal" :printed-on="printedOn" />
            </section>
        </div>
    </AdminLayout>
    <Teleport to="body"><div class="repair-print-document"><RepairPrintSlip :service="service" :statuses="statuses" :decisions="decisions" :faults="faults" :include-expenses="includePrintExpenses" :expense-total="expenseTotal" :printed-on="printedOn" /></div></Teleport>
</template>

<style>
.repair-print-document { display: none; }
@media print {
    @page { size: A4; margin: 14mm; }
    body:has(> .repair-print-document) { height: auto !important; overflow: visible !important; background: white !important; }
    body:has(> .repair-print-document) > :not(.repair-print-document) { display: none !important; }
    body > .repair-print-document { display: block !important; width: 100%; }
}
</style>
